version: "3.8"
services:
  shopsurfer_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .gateway.env
    # volumes:
    #   - ./app:/app
    ports:
      - 8000:8000
    image: shopsurfer_gateway:latest
    container_name: shopsurfer_gateway
    # command: "uvicorn main:app --host 0.0.0.0 --reload"
    # network_mode: "host"

  shopsurfer_nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    # image: nginx:latest
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    image: shopsurfer_nginx:latest
    container_name: shopsurfer_nginx
    depends_on:
      - shopsurfer_gateway
    restart: always
    # network_mode: "host"
